### ISSUE TITLE
Unable to build on ARM64 Mac

### ISSUE THREAD

**Issue by crcrworks** [blake502/balatro-mobile-maker#63]
run
```fish
chmod +x 'Balatro Mobile Maker 0.8.2-osx-arm64-expeimental'
./'Balatro Mobile Maker 0.8.2-osx-arm64-expeimental'
```
then get an error:
`fish: Job 1, './Balatro\ Mobile\ Maker\ 0.8.2…' terminated by signal SIGKILL (Forced quit)`

If use 'Balatro Mobile Maker 0.8.2 OSX x64.2-osx-x64' instead of arm64 version,
also error occurs:
```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process '7zz' with working directory '/Users/crcr/Development/balatro'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo, String, String[], String[], String, Boolean, UInt32, UInt32, UInt32[], Int32& , Int32& , Int32& , Boolean, Boolean )
   at System.Diagnostics.Process.StartCore(ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at balatro_mobile_maker.Tools.RunCommand(String, String)
   at balatro_mobile_maker.Platform.useSevenZip(String)
   at balatro_mobile_maker.Tools.useTool(ProcessTools, String)
   at balatro_mobile_maker.View.Begin()
   at balatro_mobile_maker.Program.Main(String[])
fish: Job 1, './Balatro\ Mobile\ Maker\ 0.8.2…' terminated by signal SIGABRT (Abort)
```

**Comment by kylefmohr** [comment]
Can you try the version from my latest commit in PR #61 ? @crcrworks

**Comment by blake502** [comment]
Changes from PR #61 now in the latest release.

**Comment by blake502** [comment]
Hey @crcrworks, any luck with the latest version?

This should be resolved, so I'll go ahead and close the issue. If that's not the case, I'll gladly re-open.

**Comment by madeleineostoja** [comment]
Doubt you're still maintaining this repo but I still hit this issue

Reason I'm using this rather than native android port is that the Play Store version cannot be installed on several retro handheld devices (like my Retroid Pocket Classic)

---

EDIT: Got past this issue by manually setting up `7zz` and extracting jdk, but then got stuck because `apktool.jar` now needs a wrapper script to run on Mac

**Comment by kylefmohr** [comment]
> Doubt you're still maintaining this repo but I still hit this issue
> 
> Reason I'm using this rather than native android port is that the Play Store version cannot be installed on several retro handheld devices (like my Retroid Pocket Classic)
> 
> EDIT: Got past this issue by manually setting up `7zz` and extracting jdk, but then got stuck because `apktool.jar` now needs a wrapper script to run on Mac

Hello, 

I was able to reproduce the `7zz` issue you mentioned but unable to reproduce the `apktool.jar`. If you feel comfortable running this executable, I just built it from HEAD and it seemed to work for me.

Fixed download link, since you need the .dll and other files too: 

[Archive.zip](https://github.com/user-attachments/files/30770923/Archive.zip)

Otherwise, I'm working on opening a PR to improve some features of the script, which will fix the `7z` issue, and may also help with the `apktool.jar` issue.

**Comment by kylefmohr** [comment]
@madeleineostoja PR is up, let me know if you still run into issues: https://github.com/kylefmohr/balatro-mobile-maker/tree/fix/corrupt-downloads-and-error-handling

btw, have used Lyssna (by way of UserCrowd) many times, it works well!

**Comment by madeleineostoja** [comment]
@kylefmohr thanks so much! I ended up using the python fork I found in a comment on another issue, but I'll pull your fix down and try it to confirm when I get a mo for you as well.

Great to bump into a Lyssna fan in the wild!
